name: project_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  conditional_builder: ^1.0.2
  bloc: ^7.2.0
  flutter_bloc: ^7.3.0
  dio: ^4.0.0
  hexcolor: ^2.0.5
  shared_preferences: ^2.0.5
  smooth_page_indicator: ^0.2.0
  fluttertoast: ^8.0.8
  image_picker: ^0.8.3
  iconsax: ^0.0.8
  google_nav_bar: ^5.0.5
  webview_flutter: ^2.0.3
  flutter_webview_plugin: ^0.3.8
  full_screen_image: ^1.0.2
  flutter_speed_dial: ^4.4.0
  url_launcher:
  animated_button: ^0.1.3
  animated_progress_button: ^1.0.2
  animated_splash_screen: ^1.1.0
  splashscreen: ^1.3.5
  pinch_zoom_image_last: ^0.3.2
  flutter_spinkit: ^4.1.2+1
  stacked_card_carousel: ^0.0.2+1
  bottom_picker: ^1.0.6
  flutter_datetime_picker: ^1.5.1
  date_format: ^2.0.4
  dropdownfield: ^1.0.3
  dropdown_button2: ^1.0.5
  modal_bottom_sheet: ^1.0.0+1
  flutter_launcher_icons: ^0.8.1
  pin_code_fields: ^6.1.0



  #QR code
  syncfusion_flutter_barcodes: ^19.3.55


  #firebase
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.3
  firebase_storage: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/iconLogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/one.png
    - assets/images/onboard_2.png
    - assets/images/onboard_3.png
    - assets/images/logo_ligth.png
    - assets/images/logo_dark.png
    - assets/images/vaccine.png
    - assets/images/Winter.png
    - assets/images/microscope.png
    - assets/images/Persk-bro.png
    - assets/images/Coronavir-amico.png
    - assets/images/control-panel.png
    - assets/images/healthcare.png
    - assets/images/qr.png
    - assets/images/covid-passport.png
    - assets/images/checking.png
    - assets/images/assistant.png
    - assets/images/medical-report.png
    - assets/images/alfa.png
    - assets/images/egyptpcr.png
    - assets/images/index.jpg
    - assets/images/elmoktbr.jpg
    - assets/images/CairoScan.jpg
    - assets/images/egyptpcr.jpg
    - assets/images/APLUSLAB.jpg
    - assets/images/pcrtesthome.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-VariableFont_wght.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
